name: e2e_test_app
description: App to do e2e testing for the Datadog Flutter SDK
publish_to: 'none'
version: '1.0.0'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  datadog_sdk:
    path: ../
  flutter_dotenv: ^5.0.2

dev_dependencies:
  dotenv: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
