name: datadog_gql_link
description: A package for tracking GraphQL calls in Datadog compatible with gql_link 
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  datadog_flutter_plugin: ^1.7.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  uuid: ^3.0.7
  gql: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0"
  mocktail: ^1.0.0
  datadog_common_test:
    path: ../datadog_common_test

flutter:
