name: datadog_inappwebview_tracking
description: "A package for tracking Datadog sessions in webviews create with flutter_inappwebview"
version: 1.0.0
homepage: http://datadoghq.com
repository: https://github.com/DataDog/dd-sdk-flutter

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.datadoghq.flutter.inappwebview
        pluginClass: DatadogInAppWebViewTrackingPlugin
      ios:
        pluginClass: DatadogInAppWebViewTrackingPlugin
